# Generated by Django 2.1.7 on 2019-03-27 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.IntegerField(primary_key=True, serialize=False)),
                ('agency_id', models.CharField(blank=True, max_length=20)),
                ('route_short_name', models.CharField(blank=True, default='', max_length=10)),
                ('route_long_name', models.CharField(blank=True, default='', max_length=100)),
                ('route_type', models.IntegerField(choices=[(0, 'Tram, Streetcar, Light rail'), (1, 'Subway, Metro'), (2, 'Heavy Rail'), (3, 'Bus'), (4, 'Ferry'), (5, 'Cable Tram'), (6, 'Aerial Lift'), (7, 'Funicular')])),
                ('route_color', models.CharField(blank=True, default='FFFFFF', max_length=6)),
                ('route_text_color', models.CharField(blank=True, default='000000', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('stop_id', models.IntegerField(primary_key=True, serialize=False)),
                ('stop_code', models.IntegerField(blank=True)),
                ('stop_name', models.CharField(max_length=200)),
                ('stop_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('stop_lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('zone_id', models.CharField(blank=True, max_length=50)),
                ('location_type', models.IntegerField(blank=True, choices=[(1, 'stop'), (2, 'station'), (3, 'station entrance/exit')])),
            ],
        ),
    ]
