# Generated by Django 2.2 on 2019-04-04 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.IntegerField(primary_key=True, serialize=False)),
                ('agency_id', models.CharField(blank=True, max_length=20)),
                ('route_short_name', models.CharField(blank=True, default='', max_length=10)),
                ('route_long_name', models.CharField(blank=True, default='', max_length=100)),
                ('route_type', models.IntegerField(choices=[(0, 'Tram, Streetcar, Light rail'), (1, 'Subway, Metro'), (2, 'Heavy Rail'), (3, 'Bus'), (4, 'Ferry'), (5, 'Cable Tram'), (6, 'Aerial Lift'), (7, 'Funicular')])),
                ('route_color', models.CharField(blank=True, default='FFFFFF', max_length=6)),
                ('route_text_color', models.CharField(blank=True, default='000000', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape_id', models.CharField(max_length=20)),
                ('shape_pt_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('shape_pt_lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('shape_pt_sequence', models.PositiveIntegerField()),
                ('shape_dist_traveled', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('stop_id', models.IntegerField(primary_key=True, serialize=False)),
                ('stop_code', models.CharField(blank=True, default='', max_length=10)),
                ('stop_name', models.CharField(max_length=200)),
                ('stop_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('stop_lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('zone_id', models.CharField(blank=True, max_length=50)),
                ('location_type', models.IntegerField(blank=True, choices=[(1, 'stop'), (2, 'station'), (3, 'station entrance/exit')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StopTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_id', models.CharField(max_length=20)),
                ('arrival_time', models.DurationField()),
                ('departure_time', models.DurationField()),
                ('stop_id', models.IntegerField()),
                ('stop_sequence', models.PositiveIntegerField()),
                ('stop_headsign', models.CharField(blank=True, max_length=100)),
                ('pickup_type', models.IntegerField(blank=True, choices=[(0, 'Regularly scheduled pickup'), (1, 'No pickup available'), (2, 'Phone agency to arrange pickup'), (3, 'Coordinate with driver to arrange pickup')], default=0)),
                ('drop_off_type', models.IntegerField(blank=True, choices=[(0, 'Regularly scheduled drop off'), (1, 'No drop off available'), (2, 'Phone agency to arrange drop off'), (3, 'Coordinate with driver to arrange drop off')], default=0)),
                ('shape_dist_traveled', models.FloatField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('service_id', models.CharField(max_length=10)),
                ('trip_headsign', models.CharField(blank=True, max_length=100)),
                ('direction_id', models.IntegerField(choices=[(0, 'direction 0'), (1, 'direction 1')])),
                ('block_id', models.CharField(blank=True, max_length=100)),
                ('shape_id', models.CharField(blank=True, max_length=20, null=True)),
                ('wheelchair_accessible', models.IntegerField(blank=True, choices=[(0, 'No accessibility info'), (1, 'Wheelchair-accessible'), (2, 'Not wheelchair-accessible')], default=0)),
                ('bikes_allowed', models.IntegerField(blank=True, choices=[(0, 'No bike info'), (1, 'Bikes allowed'), (2, 'Bikes not allowed')], default=0)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Route')),
            ],
        ),
    ]
