# Generated by Django 2.2 on 2019-04-04 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StopTimes',
            new_name='StopTime',
        ),
    ]
