# Generated by Django 2.1.7 on 2019-03-29 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape_id', models.CharField(max_length=20)),
                ('shape_pt_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('shape_pt_lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('shape_pt_sequence', models.PositiveIntegerField()),
                ('shape_dist_traveled', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='StopTimes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.DurationField()),
                ('departure_time', models.DurationField()),
                ('stop_sequence', models.PositiveIntegerField()),
                ('stop_headsign', models.CharField(blank=True, max_length=100)),
                ('pickup_type', models.IntegerField(blank=True, choices=[(0, 'Regularly scheduled pickup'), (1, 'No pickup available'), (2, 'Phone agency to arrange pickup'), (3, 'Coordinate with driver to arrange pickup')], default=0)),
                ('drop_off_type', models.IntegerField(blank=True, choices=[(0, 'Regularly scheduled drop off'), (1, 'No drop off available'), (2, 'Phone agency to arrange drop off'), (3, 'Coordinate with driver to arrange drop off')], default=0)),
                ('shape_dist_traveled', models.FloatField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('service_id', models.CharField(max_length=10)),
                ('trip_headsign', models.CharField(blank=True, max_length=100)),
                ('block_id', models.CharField(blank=True, max_length=100)),
                ('wheelchair_accessible', models.IntegerField(blank=True, choices=[(0, 'No accessibility info'), (1, 'Wheelchair-accessible'), (2, 'Not wheelchair-accessible')], default=0)),
                ('direction_id', models.IntegerField(choices=[(0, 'direction 0'), (1, 'direction 1')])),
                ('bikes_allowed', models.IntegerField(blank=True, choices=[(0, 'No bike info'), (1, 'Bikes allowed'), (2, 'Bikes not allowed')], default=0)),
                ('route_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Route')),
                ('shape_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Shape')),
            ],
        ),
        migrations.AlterField(
            model_name='stop',
            name='location_type',
            field=models.IntegerField(blank=True, choices=[(1, 'stop'), (2, 'station'), (3, 'station entrance/exit')], null=True),
        ),
        migrations.AlterField(
            model_name='stop',
            name='stop_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stoptimes',
            name='stop_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Stop'),
        ),
        migrations.AddField(
            model_name='stoptimes',
            name='trip_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Trip'),
        ),
    ]
