# Generated by Django 2.2 on 2019-04-05 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stoptime',
            name='shape_dist_traveled',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
