# Generated by Django 2.2 on 2019-04-03 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190328_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='stop_code',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
